name: CI

on:
  push:
    branches:
      - integration-tests
  pull_request:
    branches:
      - integration-tests


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SBT
        run: |
          mkdir -p ~/.local/sbt
          curl -fL https://github.com/sbt/sbt/releases/download/v1.9.9/sbt-1.9.9.tgz | tar xz -C ~/.local/sbt --strip-components=1
          echo "~/.local/sbt/bin" >> $GITHUB_PATH

      - name: Cache SBT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run tests
        run: sbt test
