name: ci-backend

on:
  push:
    branches:
      - integration-tests
  pull_request:
    branches:
      - integration-tests


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SBT
        run: |
          mkdir -p ~/.local/sbt
          curl -fL https://github.com/sbt/sbt/releases/download/v1.9.9/sbt-1.9.9.tgz | tar xz -C ~/.local/sbt --strip-components=1
          echo "~/.local/sbt/bin" >> $GITHUB_PATH

      - name: Cache SBT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-deps-${{ hashFiles('**/build.sbt', '**/project/build.properties', '**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-deps-

      - name: Cache SBT build
        uses: actions/cache@v4
        with:
          path: |
            target
            **/target
          key: ${{ runner.os }}-sbt-build-${{ hashFiles('src/main/**/*.scala', 'src/test/**/*.scala', '**/build.sbt', '**/project/build.properties', '**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-build-

      - name: Pull Docker images
        run: |
          docker pull testcontainers/ryuk:0.9.0
          docker pull postgres:9.6.12

      - name: Compile
        run: sbt compile test:compile

      - name: Run tests
        run: sbt test
